### ISSUE TITLE
add support for Apple iWork .iwa files

### ISSUE THREAD

**Issue by teppo-localeyes** [kubo/snzip#14]
Could you please add support for Apple iWork .iwa files. These are in Snappy's framing format but slightly non-standard. There is documentation available here:

https://github.com/obriensp/iWorkFileFormat/blob/master/Docs/index.md#snappy-compression

**Comment by teppo-localeyes** [comment]
Here is a sample file.

[Document.iwa.zip](https://github.com/kubo/snzip/files/336559/Document.iwa.zip)

**Comment by kubo** [comment]
I'll add it at the next weekend. File format detection will not be supported because the iwa format has no file signature. `-t iwa` option is required to compress/uncompress files.

**Comment by kubo** [comment]
Sorry. I had forgot it. I did it just now. (bcf1150)
I tested it with the file you attached.
```shell
$ unzip Document.iwa.zip
$ cp Document.iwa Document.iwa.bak
$ snzip -t iwa -d Document.iwa       # uncompress Document.iwa
$ snzip -t iwa Document              # compress Document and create Document.iwa
$ cmp Document.iwa Document.iwa.bak  # verify whether snzip makes same contents.
```

Could you test it with an iwa file whose length is larger than 65536?
The maximum length of uncompressed data in a chunk is 65536 in snappy-framed format.
See: https://github.com/google/snappy/blob/1.1.3/framing_format.txt#L90-L92
However I'm not sure that it is same with the iwa format.

**Comment by teppo-localeyes** [comment]
Works great even with files larger than 65536. Thanks!

**Comment by davejacobs** [comment]
I'm getting `Unknown file format name iwa`. Is there an extra step I need to do?

I'm using `snzip 1.0.3` and `snappy 1.1.3`.

**Comment by davejacobs** [comment]
Ah I see, it's not out yet. Would you mind cutting a release when you get a chance, @kubo? (This is really great!)

**Comment by kubo** [comment]
@davejacobs I'll make a new release next weekend.

**Comment by davejacobs** [comment]
Okay, thanks! I look forward to trying it out.

**Comment by kubo** [comment]
@davejacobs 
snzip 1.0.4 was released.

**Comment by davejacobs** [comment]
Thanks! 🎉

**Comment by svpv** [comment]
Would you please tag the release?

**Comment by golanlevin** [comment]
This saved my butt, and helped me recover my mom's memoirs. Thanks for the .iwa compatibility.

**Comment by codecowboy** [comment]
@golanlevin @teppo-localeyes What are the steps to get an iwa into a human readable format or XML if extraction results in a protobuf stream? Is it possible to end up with XML after doing:

```
snzip -t iwa -d Document.iwa
//what next?
```

My understanding is that iwa fies are XML files which are converted to protobuf streams and then compressed using snappy. Is it possible to recover the original XML? I've never used protobuf or snappy and installed snzip using brew. Am on MacOS Ventura 13.4 (Apple Silicon)
