### ISSUE TITLE
Unknown file header when try to decode raw file

### ISSUE THREAD

**Issue by asarubbo** [kubo/snzip#16]
```
# echo "foo" > file.txt
# snzip -k -t raw file.txt
# snzip -k -d -c file.txt.raw
Unknown file header
```
I'm using snappy-1.1.3 with snzip-1.0.3
Can you reproduce?

**Comment by kubo** [comment]
The automatic file format detection doesn't work for raw format because raw format doesn't have explicit file signature. You need to add `-t raw` to decode.
I'll fix README.md later.
