### ISSUE TITLE
How can I build snunzip

### ISSUE THREAD

**Issue by spetsnaz84** [kubo/snzip#21]
When I build the project, I only get the snzip executable.

**Comment by kubo** [comment]
Copy snzip to snunzip.
If the executable name includes `un`, it acts as snunzip.

**Comment by spetsnaz84** [comment]
OK. I guess it would be easy for the Makefile to just generate an snunzip as well then, no ?

**Comment by kubo** [comment]
33c5942ba51eff66d573882fa6009e05f83932d9 fixed this issue.
`make install` installs `snunzip` and `snzcat` also as bzip2 does.

**Comment by spetsnaz84** [comment]
Great ! Thanks.
